name: Build and Push Docker Images

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build frontend Image
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gradlink-client:latest .

      - name: Push frontend Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/gradlink-client:latest

      - name: Build backend Image
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gradlink-server:latest .

      - name: Push ackend Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/gradlink-server:latest